### ISSUE TITLE
How external traffic reaches VMs inside a compute node?

### ISSUE THREAD

**Issue by flozanorht** [openstack-k8s-operators/docs#84]
The diagram https://github.com/openstack-k8s-operators/docs/blob/main/images/network_diagram.jpg gives no clue about it. As the only "external" network there is the OpenShift cluster network (or whenever OpenShift ingress controllers and default LB services get their VIPs) it seems it has to be forwarded by OpenShift worker nodes, but how?

**Comment by stuggi** [comment]
@slawqo or @karelyatin can better answer that.

**Comment by karelyatin** [comment]
I think i am seeing this diagram first time. But yes you are right it's missing external network references on compute node so that needs to be fixed.

With default dvr configuration, external interface is required on the compute nodes. Right now with the validated architecture dev setup we are using ctlplane network as external n/w for FIP traffic. So VMS with FIPs get's accessible over this network. And SNAT for VMS without FIP goes via ocp worker nodes over the same ctlplane interface(enp7s0).

**Comment by stuggi** [comment]
@karelyatin so for a general nw architecture it would be like https://github.com/openstack-k8s-operators/docs/pull/86
